spring.application.name=restaurant-server

spring.datasource.url=jdbc:postgresql://localhost:5432/app-mozo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=${SECRET_KEY}

server.port=8081


