spring.application.name=restaurant-server
server.port=8081

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/app-mozo}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Security
security.jwt.secret-key=${SECRET_KEY:dev-secret-key-at-least-32-chars-long!!}
